forge "http://forge.puppet.com"

mod 'puppetlabs/concat'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/firewall'
mod 'lwf/remote_file'
mod 'stm/debconf'
mod 'dalen-dnsquery'
mod 'puppetlabs/ntp'
mod 'puppetlabs/puppetdb'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/dsc'
mod 'puppetlabs/reboot'
mod 'puppetlabs/chocolatey'
mod 'puppetlabs/powershell'
mod 'puppetlabs-registry'
mod 'puppet/r10k'
mod 'puppetlabs/ruby'
mod 'puppetlabs/gcc'
mod 'puppet/make'
mod 'puppetlabs/inifile'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/git'
mod 'gentoo/portage'
mod 'saz/timezone'
mod 'ajjahn-dns',
  :git    => 'https://github.com/ajjahn/puppet-dns',
  :commit => '57946eb'
mod 'puppet-filemapper'
mod 'puppet-boolean'
mod 'camptocamp-kmod'
mod 'example42-network'
mod 'pcfens/filebeat'
mod 'elastic/logstash'
mod 'elastic/elasticsearch'
mod 'elastic/kibana'
mod 'elastic/elastic_stack'
mod 'puppetlabs/java'
mod 'puppet/archive'
mod 'puppet/nginx'
mod 'puppet/tea'
mod 'puppet/wget'
mod 'leinaddm/htpasswd'
mod 'puppet/yum'
mod 'richardc/datacat'
mod 'sensu/sensu'
mod 'puppet-rabbitmq'
mod 'camptocamp-systemd'
mod 'puppet/staging'
mod 'yelp/uchiwa'
mod 'puppetlabs/apt'
#mod 'garethr-erlang',
#  :git    => 'https://github.com/garethr/garethr-erlang',
#  :commit => '23fb75b'
mod 'arioch/redis'
mod 'herculesteam-augeasproviders_sysctl'
mod 'herculesteam-augeasproviders_core'
mod 'stahnma/epel'
mod 'puppetlabs-mysql'
mod 'puppetlabs-translate'
mod 'dwerder/graphite'
mod 'puppet/grafana'
mod 'puppetlabs-docker', '2.0.0'
mod 'devsec-suricata'
